import { createContext } from "react";
  const lightTheme = JSON.parse(`{
    "primary": "#705D00",
    "onPrimary": "#FFFFFF",
    "primaryContainer": "#FFE16E",
    "onPrimaryContainer": "#221B00",
    "primaryFixed": "#FFE16E",
    "onPrimaryFixed": "#221B00",
    "primaryFixedDim": "#E9C400",
    "onPrimaryFixedVariant": "#544600",
    "secondary": "#675E40",
    "onSecondary": "#FFFFFF",
    "secondaryContainer": "#EFE2BC",
    "onSecondaryContainer": "#211B04",
    "secondaryFixed": "#EFE2BC",
    "onSecondaryFixed": "#211B04",
    "secondaryFixedDim": "#D2C6A1",
    "onSecondaryFixedVariant": "#4E462A",
    "tertiary": "#44664D",
    "onTertiary": "#FFFFFF",
    "tertiaryContainer": "#C6ECCD",
    "onTertiaryContainer": "#00210E",
    "tertiaryFixed": "#C6ECCD",
    "onTertiaryFixed": "#00210E",
    "tertiaryFixedDim": "#AAD0B2",
    "onTertiaryFixedVariant": "#2D4E37",
    "error": "#BA1A1A",
    "onError": "#FFFFFF",
    "errorContainer": "#FFDAD6",
    "onErrorContainer": "#410002",
    "outline": "#7C7767",
    "background": "#FFFBFF",
    "onBackground": "#1D1B16",
    "surface": "#FFF9EF",
    "onSurface": "#1D1B16",
    "surfaceVariant": "#EAE2CF",
    "onSurfaceVariant": "#4B4739",
    "inverseSurface": "#33302A",
    "inverseOnSurface": "#F6F0E7",
    "inversePrimary": "#E9C400",
    "shadow": "#000000",
    "surfaceTint": "#705D00",
    "outlineVariant": "#CDC6B4",
    "scrim": "#000000",
    "surfaceContainerHighest": "#E8E2D9",
    "surfaceContainerHigh": "#EDE7DE",
    "surfaceContainer": "#F3EDE4",
    "surfaceContainerLow": "#F9F3EA",
    "surfaceContainerLowest": "#FFFFFF",
    "surfaceBright": "#FFF9EF",
    "surfaceDim": "#DFD9D0"
  }`);


export const ThemeContext = createContext(lightTheme)